#!/bin/bash -ex

# tools/install-tool-dependencies
#
# Install Rust and Cargo components used by tool scripts, which are not part of
# Cargo.toml.

rustup toolchain install nightly
rustup component add clippy rustfmt
cargo +nightly install cargo-udeps
