name: Update Rust nightly
on:
    workflow_dispatch:
    schedule:
        # Nothing magic here, I just wanted to avoid the midnight thundering
        # herd on the first of each month.
        - cron: '0 5 8 * *'

jobs:
    nightly-update:
        name: Update Rust nightly
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: date +nightly-%Y-%m-%d > rust-toolchain
            - run: rustup install --profile minimal "$(< rust-toolchain)"
            - run: rustup component add clippy rustfmt
            - run: cargo install cargo-udeps
            - run: tools/checks
            - uses: peter-evans/create-pull-request@v3
              with:
                commit-message: Update Rust nightly version.
                branch: rust-nightly-update
                title: Update Rust nightly version
                body: |
                    If these changes look good, merge this pull request to
                    update to the latest Nightly as of today.
                    
                    Automatically generated by the nightly-rust-update workflow.
